; *********************** ltostr.mac *******************
;
; ltostr dwmem, dmem, endchar
;   盢dwmem蛮舱Τ腹计锣传ASCII计dmem
;   dwmem   : 蛮舱
;   dmem    : ASCII计
;   endchar : ﹃挡才腹(盽计,肚)
;
%ifndef LTOSTR_MAC
%define LTOSTR_MAC
%MACRO  ltostr  3
        PUSHA                  ;纗ㄓ既竟戈
        MOV     CX, 0          ;ASCII计计璸计
        MOV     EAX, [%1]      ;蛮舱ず
        CMP     EAX, 0         ;EAX>=0?
        JGE     %%pos          ;琌
        NEG     EAX            ;EAX=-EAX
        MOV     DL, '-'        ;DL='-'
        MOV     [%2], DL       ;ASCII计ず'-'
        JMP     %%next
%%pos:
        MOV     DL, ' '        ;DL=' '
        MOV     [%2], DL       ;ASCII计ず' '
%%next:
        MOV     EDX, 0         ;EDX=0
        MOV     EBX, 10        ;EBX=10
%%loop2:
        DIV     EBX            ;EDX:EAX/EBX
        PUSH    EDX            ;舼緇计
        INC     CX             ;ASCII计计糤
        MOV     EDX, 0         ;EDX=0
        CMP     EAX, 0         ;坝=0?
        JNZ     %%loop2        ;
;
        MOV     SI, %2         ;SI=ASCII计才腹
        INC     SI             ;ASCII计
%%loop3:
        POP     EAX            ;舼緇计EAX
        ADD     AL, 30H        ;计锣传ASCII计
        MOV     [SI], AL       ;SI
        INC     SI             ;SI=ASCII计
        LOOP    %%loop3        ;膥尿
        MOV     BYTE [SI], %3  ;﹃挡才腹
        POPA                   ;確ㄓ既竟戈
%ENDMACRO
%endif
