; ********************** showdw.mac ******************
;
; showdw  dmem
;   將 dmem 記憶體字組內含值以16進位數字顯示於螢幕
;   dmem : 記憶體雙字組位址
;
%ifndef    SHOWDW_MAC
%define    SHOWDW_MAC
%MACRO     showdw   1              ;一個參數,字組位址
;
%include "..\mymacro\showbyte.mac"
;
        PUSHA                      ;儲存原來暫存器資料
        showbyte %1+3
        showbyte %1+2
        showbyte %1+1
        showbyte %1
        POPA                       ;恢復原來暫存器資料
%ENDMACRO
%endif
